Resources:
  DynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${file(./serverless.env.yml):${opt:stage, self:provider.stage}.STAGE}-userData
      AttributeDefinitions:
        - AttributeName: tenantId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: tenantId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
  DynamoDBIamPolicy:
    Type: AWS::IAM::Policy
    DependsOn: DynamoDbTable
    Properties:
      PolicyName: ${file(./serverless.env.yml):${opt:stage, self:provider.stage}.STAGE}-lambda-dynamodb
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
            Resource: 
              Fn::GetAtt: [ DynamoDbTable, Arn ]
      Roles:
        - Ref: IamRoleLambdaExecution