from db.models.base import Base
from db.models.actor import Actor
from db.models.asset_cost_fraud import AssetCostFraud
from db.models.asset_cost_record import AssetCostRecord
from db.models.asset_ddos_cost import AssetDdosCost
from db.models.asset_downtime_industry import AssetDowntimeIndustry
from db.models.business_impact import BusinessImpact
from db.models.company_threat_scenario import CompanyThreatScenario
from db.models.company import Company
from db.models.control_assessment import ControlAssessment
from db.models.control_attribute import ControlAttribute
from db.models.control_family_assessement_progress import ControlFamilyAssessmentProgress
from db.models.control_sme_estimated import ControlSmeEstimated
from db.models.financial import Financial
from db.models.industry import Industry
from db.models.mitre_attack_technique_control_attribute import MitreAttackTechniqueControlAttribute
from db.models.mitre_attack_technique import MitreAttackTechnique
from db.models.score_result import ScoreResult
from db.models.score import Score
from db.models.tef_company_size import TefCompanySize
from db.models.tef_industry import TefIndustry
from db.models.threat_scenario_control_attribute import ThreatScenarioControlAttribute
from db.models.threat_scenario_mitre_attack_technique import ThreatScenarioMitreAttackTechnique
from db.models.threat_scenario import ThreatScenario
from db.models.vector import Vector